#!/bin/sh
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
$JAVA_HOME/bin/javac -Xlint:-options -source 6 -target 6 HelloWorld.java
$JAVA_HOME/bin/javac -g -Xlint:-options -source 6 -target 6 -cp ../std/bin ComponentTest.java